name: Фича
description: Предложить улучшение или новую функциональность
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему решает
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Предлагаемое решение
